### ISSUE TITLE
testing todo

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/word-game#8]
* [x] make clues
* [x] generate clue data
* [x] points!
* [x] load clue data in app
* [x] render JSON of user guesses
* [x] link to (and create) google form for feedback
* [x] get a granny tester to make us data
